### ISSUE TITLE
Help wanted! Why does the paper mention using RAT as an encoder, while the code uses RGAT as an encoder?

### ISSUE THREAD

**Issue by kanseaveg** [rhythmcao/astormer#1]
I feel confused when reading the paper and code. I found that the encoder used in the paper is different from the one used in the code. Which one should I follow? Thank you.
![image](https://github.com/rhythmcao/astormer/assets/80022154/d0ac844a-274b-47cd-9d62-6614e427ad3e)
![image](https://github.com/rhythmcao/astormer/assets/80022154/c8135a18-545d-4238-b674-0bcc707ffd2e)

**Comment by rhythmcao** [comment]
RGAT and RATSQL are the same.
