### ISSUE TITLE
Pretrained on spider data

### ISSUE THREAD

**Issue by Saivignesh-05** [rhythmcao/astormer#3]
Hello @rhythmcao, Do you have a previously trained model on the spider dataset, so that I can directly use it for inference. I'm only interested in using different metrics to check how different models perform. So it will be of real help if u can add the pretrained model directly useful for inference. Thanks in advance

**Comment by rhythmcao** [comment]
Codes and models are not maintained anymore, you can train one by yourself from scratch in a few hours.
